version: '3'

services:
  postgres:
      image: postgres
      restart: always
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
      ports:
          - "5432:5432"
      volumes:
          - "./data:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root